=== HarsanyiBalazs/HD9DOJ_XML/HD9DOJ_1119/xPathHD9DOJ/studentHD9DOJ.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="hallgatok">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="hallgato">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="keresztnev" type="string" />
              <xs:element name="vezeteknev" type="string" />
              <xs:element name="becenev" type="string" />
              <xs:element name="kor" type="unsignedByte" />
            </xs:sequence>
            <xs:attribute name="id" type="unsignedByte" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== HarsanyiBalazs/HD9DOJ_XML/HD9DOJ_1119/xPathHD9DOJ/src/xpathhd9doj1119/studentHD9DOJ.xml
<?xml version="1.0" encoding="UTF-8"?>

<hallgatok xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="studentHD9DOJ.xsd">
    <hallgato id="01">
        <keresztnev>Pal</keresztnev>
        <vezeteknev>Kiss</vezeteknev>
        <becenev>Web Developer</becenev>
        <kor>21</kor>
    </hallgato>
    <hallgato id="02">
        <keresztnev>Piroska</keresztnev>
        <vezeteknev>Vigh</vezeteknev>
        <becenev>Java Programozo</becenev>
        <kor>20</kor>
    </hallgato>
    <hallgato id="03">
        <keresztnev>Ferenc</keresztnev>
        <vezeteknev>Nagy</vezeteknev>
        <becenev>associate professor</becenev>
        <kor>19</kor>
    </hallgato>
</hallgatok>
